class locate():
    
    xpath = "//*[@id='password']"
    Home_page_validate = "/html/body/div/div/div[2]/form/button/span"
    Dashboard_validate = "//a[@href='/dashboard']"
    actual_result = "/html/body/div[1]/div[1]/div/div[2]/div[1]/div"
    xpath_dashboard = "/html/body/div[1]/div[1]/div/nav/ul/li[1]/a"
    wallet_allow = "/html/body/div[1]/div[1]/div/div[2]/div[2]/div[1]/button"
    Login_validator_Link_text = "Claim Testnet "
    starkey_install_button_click = "/html/body/div[2]/ol/li/div/div/a/button/span[1]" # click operation
    click_on_chrome = "/html/body/div/div[3]/section[1]/div/div/div/div[1]/div/div/div[2]/div/div/a[1]"
    add_to_chrome = "//button[@id='add-chrome']" #"/html/body/c-wiz/div/div/main/div/section[1]/section/div/div[1]/div[2]/div/button/span[6]" # //*[@id="yDmH0d"]/c-wiz/div/div/main/div/section[1]/section/div/div[1]/div[2]/div/button/span[4]
    Click_on_Connect_wallet = "//span[text()='Connect wallet']" # "/html/body/div[1]/div[1]/div/div[2]/div[2]/div[1]/button/span"
    Get_a_new_wallet_click = "//*[@id='root']/div/div[1]/div/div[2]/div[2]/div[2]/button[1]"
    Enter_private_key = "//*[@id='privateKeyInput']"
    Enter_user_name = "//*[@name='username']"
    Enter_set_password = "//*[@name='password']"
    Enter_confirm_password = "//*[@name='confirmPassword']"
    Click_next_button = "//*[@id='create-next-btn']"
    skiptab = "//*[@id='root']/div/div[1]/div/div[2]/div/div[2]/div[1]/button"
    open_wallet = "//*[@id='root']/div/div[1]/div/div[2]/div/div[2]/button"
    reconnect_wallet = "/html/body/div[1]/div[2]/div/div/div[2]/div[1]/div[2]/button"
    Allow_button = "//*[@id='root']/div/div[1]/div/div[2]/div/div[2]/div[2]/button[2]"
    click_on_trade = "//*[text()='Trade']" # drop down
    Trade_to_swap_click = "(//a[text()='Swap'])[1]"
    select_market = "/html/body/div[1]/div[2]/div/div/div[1]/div[1]/button[1]/div/div" # drop down
    select_market_supra = "//span[@class='text-xs sm:text-base' and text()='SUPRA-USDT']"
    # Click_on_CLMM = "/html/body/div[1]/div[2]/div/div[2]/div/div/div[1]/button[2]"
    Transaction_failed_ok = "//*[@text()='OK']"
    Transaction_failed = "//*[text()='Transaction failed']"
    Create_pool_min_print = "(//*[@class='text-center'])[1]"
    Create_pool_max_print = "(//*[@class='text-center'])[2]"
    Live_Token_price = "//*[@CLASS='text-white']"
    x_deposit_Ratio_text = "(//div[@class='text-sm'])[3]"
    y_deposit_Ratio_text = "(//div[@class='text-sm'])[4]"
    sender_element = "(//a[starts-with(@href, '/address/')])[1]"
    receiver_element = "(//a[starts-with(@href, '/address/')])[2]"
    Swap_x_Exchange = "(//*[@class='text-lighterGray w-fit border border-lightGray rounded-[0.625rem] px-2 py-1 hover:ui-border-white/50 transition-all duration-500 ease-smooth whitespace-nowrap'])[1]" # "(//div[@class='flex gap-1.5 items-center pr-8 relative w-fit'])[1]"
    Swap_y_Exchange = "(//*[@class='text-lighterGray w-fit border border-lightGray rounded-[0.625rem] px-2 py-1 hover:ui-border-white/50 transition-all duration-500 ease-smooth whitespace-nowrap'])[2]"
    Swap_x_Valuee = "(//*[@id='decimal-input'])[1]"
    Swap_y_Valuee = "(//*[@id='decimal-input'])[2]"
    Swap_button = "(//button[@type='button'])[9]"
    Token_search = "//*[@placeholder='Search']"
    x_one_dollar_value = "(//*[@id='decimal-input'])[1]"
    y_one_dollar_value = "(//*[@id='decimal-input'])[2]"
    acknow_click = "//button[@id='terms']" # or //*[text()='Swap']" # /html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[2]/div[3]/div/button
    Connect_wallet = "/html/body/div[1]/div[2]/div/div[2]/div/div/div[3]/div[2]/button/span"
    wallet_msg_display = "//*[@class='break-all whitespace-pre-wrap flex-grow text-custom-black dark:text-custom-white']"
    swap_button_direct = "//span[text()='Swap']" #, "/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[2]/div[2]/button/span" # "/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[2]/div[3]/button" # "//button[@class='style_button__bI4Ti ui-group ui-relative ui-cursor-pointer ui-rounded-xl ui-overflow-hidden ui-font-semibold ui-flex ui-gap-2.5 ui-items-center ui-w-fit hover:ui-brightness-[1.15] ui-transition-[filter] ui-duration-500 ui-ease-smooth ui-justify-center ui-px-3.5 md:ui-px-5 ui-py-2 md:ui-py-2.5 ui-h-11 ui-bg-theme-gradient ui-w-full']" 
    starkey_confirm_or_allow = "//button[normalize-space(text())='Confirm' or normalize-space(text())='Connect' or normalize-space(text())='Allow']" # "//*[text()='Confirm'] | //*[text()='Allow']"
    starkey_deny = "//*[text()='Deny']"
    starkey_deny_popup_msg = "//*[text()='Transaction rejected by user']"
    TX_validation = "//span[text()='View in Explorer' or text()='Close']"
    TX_submitted = "/html/body/div[4]/div/div[1]/h2"
    TX_View = "//a[starts-with(@href, 'https://testnet.suprascan.io/')]"
    view_exp = "//*[text()='View in Explorer']"
    main_page_login = "(//*[text()='Login'])[2]"
    User_TX_status = "//*[@class='flex w-full items-center justify-start gap-1 text-lg font-medium text-txt-success-light dark:text-txt-success mobile:w-auto']"
    VM_status = "(//*[@class='flex items-end text-sm [word-break:break-word] mobile:text-base undefined'])[5]"
    Swap_error_msg = "//*[text()='Amount is too low']"
    click_on_earn = "//*[text()='Earn']"
    click_on_pool = "//*[text()='Pools'][1]"
    click_on_liquidity = "//*[text()='Add Liquidity']" # | //*[text()='Add liquidity']"
    click_on_explorepools = "//*[text()='Explore Pools']"
    click_on_base_token_pair = "(//span[@class='truncate'])[1]"
    click_on_Token_x_y = "/html/body/div[4]/div/div[2]/div[1]/input"
    element_visiibility_x_y = "//div[@class='space-y-0.5 leading-[1.15] flex-grow']"
    click_on_base_query_pair = "(//span[@class='truncate'])[2]"
    pool_type = "//*[text()='Concentrated']"
    fee_tier_dropdown = "//*[text()='Select fee tier']"
    fetch_fee_tier = "//div[@role='option']"
    click_on_continue = "//span[text()='Continue']"
    my_position = "/html/body/div[1]/div[2]/div/div[3]/div/div[1]/div[1]/button[2]"
    # total_liqudity = "//*[text()='Total Liquidity']"
    click_on_po = "//*[@class='h-4 w-4 shrink-0 transition-transform duration-200 chevronIcon']"
    click_on_arrow = "/html/body/div[1]/div[2]/div/div[3]/div/div[3]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/a"
    click_on_increase = "//*[text()='Increase']"
    enter_input = "(//*[@id='decimal-input'])[1]"
    Increase_liquidity = "//*[text()='Increase liquidity']"
    Remove_liquidity1 = "//*[normalize-space(text())='Remove']"
    slider = "//*[@role='slider' and @aria-valuenow='25']"
    Remove_liqu = "//*[text()='Remove Liquidity']"
    wallet_already_have_btn = "//button[contains(text(), 'I already have one')]"
    private_key_btn = "//*[text()='Private Key']"
    network_dropdown = "//*[text()='Network']"
    supra_network_option = "//*[text()='Supra']"
    next_btn = "//button[text()='Next']"
    all_networks_tab = "//span[text()='All Networks']"
    testnet_btn = "//button[text()='Testnet']"
    password_input = "//*[@id='password-input']"
    login_failed_msg = "//*[contains(text(), 'Invalid password. Please try again.')]"
    hash_text = "/html/body/div[1]/div[1]/div/div[2]/div[2]/div[1]/button/span[2]"
    pool_page_title = "//p[text()='Liquidity Pools']"
    create_pool_btn = "//*[text()='Create Pool']"
    clear_btn = "//span[text()='Clear']"
    base_token_dropdown = "(//span[text()='Select Token'])[1]"
    quote_token_dropdown = "/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div/div[1]/div[2]/div[2]/button/div/span"
    pool_not_found_error = "//*[text()='Pool Not Found']"
    token_search_input = "//*[@placeholder='Search' and not(text()='Add Token')]"
    standard_tab = "//span[text()='Standard']"
    concentrated_tab = "//span[text()='Concentrated']"
    event_pointer = "//*[@class='text-sm w-full [&_.price-total-conversion>button+div]:pointer-events-none']"
    pool_exists_text = "//*[text()='Add Liquidity']"
    amount_input = "(//input[@id='decimal-input'])[1]"
    custom_range_tab = "//*[text()='Custom Range']"
    create_pool_final_btn = "//span[text()='Create Pool']" # "(//*[text()='Create Pool'])[2]"
    provide_liquidity = "//*[text()='Provide Liquidity']"
    y_price_usd = "/html/body/div[1]/div[2]/div/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[1]/div[1]/div/input"
    y_price_usd_Verify = "/html/body/div[1]/div[2]/div/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[1]/div[1]/p/div/button"
    x_price_usd = "/html/body/div[1]/div[2]/div/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[1]/div[1]/div[1]/div/input"
    x_price_usd_Verify = "/html/body/div[1]/div[2]/div/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[1]/div[1]/div[1]/p/div/button"
    Transaction_close = "//*[text()='Close']"
    click_onPos = "//*[normalize-space(text())='Explore Pools']"
    Nopositionfound = "//*[normalize-space(text())='No positions found']"
    RecreatePool_loc = "//*[text()='Set initial price']"
    Title_click = "//*[@aria-label='Dexlyn']"
    Homepage_claim = "//*[text()='Claim']"
    wallet_password = "//*[@placeholder='Password']"
    wallet_login_btn = "//*[text()='Log in']"
    wallet_popup_msg = "//*[@class='break-all whitespace-pre-wrap flex-grow text-custom-black dark:text-custom-white']"
    msg_pop_up_below = "//*[@class='ui-text-sm ui-opacity-90']"

    positions_text = "//*[text()='Positions']"
    filter_by_token = "//*[text()='Filter by Token']"
    ethereum_input = "/html/body/div[3]/div/div/div[1]/input"
    
    earn_tab = "//*[@id='earn-tab']"
    pool_button = "//*[@id='pool-button']"
    tick = "/html/body/div[3]/div/div/div[2]/div/div/div/div/div/div/div[2]/div/button"
    supra_input = "/html/body/div[3]/div/div/div[1]/input"
    # supra_tick = "/html/body/div[3]/div/div/div[2]/div/div/div/div/div/div/div[2]/div/button"
    v3_pool = "/html/body/div[1]/div[2]/div/div[2]/div/div/div[1]/div/label[3]"
    swap_table_row = "/html/body/div[1]/div[2]/div/div[3]/div/div/div/table/tbody/tr[1]/td[6]/div/a[2]/span"
    clmm_button = "/html/body/div[1]/div[2]/div/div[2]/div/div/div[1]/button[2]"
    y_usd_input = "/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[2]/div[1]/div[3]/div[1]/div[1]/div/input"
    # y_usd_button = "/html/body/div[1]/div[2]/div/div[2]/div/div/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]/button"
    x_usd_input = "/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/input"
    x_usd_button = "/html/body/div[1]/div[2]/div/div[2]/div/div/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button"
    terms_checkbox = "terms"

    High_price_impact_msg = "//div[@class='flex items-center gap-2 font-bold pt-4 text-yellow-500']"
    y_amount_validate = "/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/input"

    slipage_check = "//*[@class='ui-text-grayWhite hover:ui-text-white']"
    slipage_check_2 = "//label[.//input[@value='2%']]"
    savebtn = "//*[text()='Save']"

    Createpoolsetprice = "/html/body/div[1]/div[2]/div/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[1]/div[1]/div[1]/div/input"

    Remove_max = "//button[text()='MAX']"

# class position_increase:

    Index_8 = "//*[contains(., 'Active')]//a[contains(@href, '?index=8')]" # "//a[@href='/liquidity/0xe503d43f0506dba536994624982ffa873526d9ad6c3ada26a3377df03940f8c1?index=8' and contains(text(), 'Active')]"
    Index_7 = "//*[contains(., 'Active')]//a[contains(@href, '?index=7')]" # "//a[@href='/liquidity/0xe503d43f0506dba536994624982ffa873526d9ad6c3ada26a3377df03940f8c1?index=7' and contains(text(), 'Active')]"
    Index_6 = "/html/body/div[1]/div[2]/div/div[3]/div/div[3]/div/div[2]/div/div/div/div/div/div/div/div[2]/a" # "//*[contains(., 'Active')]//a[contains(@href, '?index=6')]" # "//a[@href='/liquidity/0xe503d43f0506dba536994624982ffa873526d9ad6c3ada26a3377df03940f8c1?index=6' and contains(text(), 'Active')]"
    Index_6inactive = "//*[contains(., 'InActive')]//a[contains(@href, '?index=6')]" # "//a[@href='/liquidity/0xe503d43f0506dba536994624982ffa873526d9ad6c3ada26a3377df03940f8c1?index=6' and contains(text(), 'InActive')]"